FROM docker.io/gvenzl/oracle-xe:latest

# Copie o script de inicialização para dentro do contêiner
COPY entrypoint.sh /entrypoint.sh

# Defina as permissões de execução para o script
RUN chmod +x /entrypoint.sh

# Defina o comando padrão a ser executado quando o contêiner for iniciado
CMD ["/entrypoint.sh"]
