version: '3.8'

services:
  novoOracle:
    image: docker.io/gvenzl/oracle-xe:latest
    container_name: 'novoOracle'
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: teste
      APP_USER: usertest
      APP_USER_PASSWORD: teste
    volumes:
      - oracle_data:/opt/oracle/oradata
      - oracle-logs:/opt/oracle/logs
    networks:
      - oracle-net

volumes:
  oracle_data:
    driver: local
  oracle-logs:

networks:
  oracle-net:
