version: '3.8'
      
volumes:
  oracle_data:
    driver: local

networks:
  postgres-net:

services:
  postgres_db:
    image: postgres
    container_name: 'postgres_db'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: teste
      APP_USER: postgres
      APP_USER_PASSWORD: teste
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    networks:
      - postgres-net

  
