--ALTER TABLE EXAMES ADD CONSTRAINT FK_ID_TIPO FOREIGN KEY (ID_TIPO) REFERENCES TIPO_EXAME (ID_TIPO);
--ALTER TABLE EXAMES DROP COLUMN ID_TIPO; USAR ESSE DROP SE JA TIVER ADICIONADO O TIPO.


ALTER TABLE EXAMES ADD CONSTRAINT FK_ID_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID);

//////////////

ALTER TABLE PACIENTES ADD CONSTRAINT FK_ID_CLINICA FOREIGN KEY (ID_CLINICA) REFERENCES CLINICAS (ID_CLINICA);

//////////////

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ID_LOGRADOURO FOREIGN KEY (ID_LOGRADOURO) REFERENCES LOGRADOURO (ID_LOGRADOURO);

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ID_BAIRRO FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO (ID_BAIRRO);

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ID_UF FOREIGN KEY (ID_UF) REFERENCES UF (ID_UF);

//////////////

ALTER TABLE CLINICAS ADD CONSTRAINT FK_CNPJ FOREIGN KEY (ID_CNPJ) REFERENCES CNPJ (CNPJ);

//////////////

ALTER TABLE CNPJ ADD CONSTRAINT FK_ID_ENDERECOS FOREIGN KEY (ID_ENDERECOS) REFERENCES ENDERECO (ID_ENDERECO);

//////////////

ALTER TABLE PROFISSIONAL_SAUDE ADD CONSTRAINT FK_ID_CLINICA_PROFISSIONAL FOREIGN KEY (ID_CLINICA) REFERENCES CLINICAS (ID_CLINICA);

ALTER TABLE PROFISSIONAL_SAUDE ADD CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE PROFISSIONAL_SAUDE ADD CONSTRAINT FK_ID_FUNCAO FOREIGN KEY (ID_FUNCAO) REFERENCES FUNCAO (ID_FUNCAO);

ALTER TABLE PROFISSIONAL_SAUDE ADD CONSTRAINT FK_COD_SIGLA FOREIGN KEY (COD_SIGLA) REFERENCES SIGLA (COD_SIGLA);

//////////////

ALTER TABLE FUNCAO ADD CONSTRAINT FK_ID_HORARIO FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO (ID_HORARIO);

//////////////

ALTER TABLE SIGLA ADD CONSTRAINT FK_ID_TIPO_SIGLA FOREIGN KEY (ID_TIPO_SIGLA) REFERENCES TIPO_SIGLA (ID_TIPO_SIGLA);

//////////////

ALTER TABLE IMAGENS ADD CONSTRAINT FK_EXAME FOREIGN KEY (ID_EXAME) REFERENCES EXAMES(ID_EXAMES);