
ALTER TABLE TIPO_EXAME ADD CONSTRAINT ID_TIPOPK PRIMARY KEY(ID_TIPO);

ALTER TABLE EXAMES ADD CONSTRAINT ID_EXAMESPK PRIMARY KEY(ID_EXAMES);

ALTER TABLE LOGRADOURO ADD CONSTRAINT ID_LOGRADOUROPK PRIMARY KEY(ID_LOGRADOURO);

ALTER TABLE ENDERECO ADD CONSTRAINT ID_ENDERECOPK PRIMARY KEY(ID_ENDERECO);

ALTER TABLE BAIRRO ADD CONSTRAINT ID_BAIRROPK PRIMARY KEY(ID);

ALTER TABLE UF ADD CONSTRAINT ID_UFPK PRIMARY KEY(ID_UF);

ALTER TABLE CLINICAS ADD CONSTRAINT ID_CLINICAPK PRIMARY KEY(ID_CLINICA);

ALTER TABLE CNPJ ADD CONSTRAINT CNPJPK PRIMARY KEY(CNPJ);

ALTER TABLE PROFISSIONAL_SAUDE ADD CONSTRAINT CPFPK PRIMARY KEY(CPF);

ALTER TABLE FUNCAO ADD CONSTRAINT ID_FUNCAOPK PRIMARY KEY(ID_FUNCAO);

ALTER TABLE HORARIO ADD CONSTRAINT ID_HORARIOPK PRIMARY KEY(ID_HORARIO);

ALTER TABLE SIGLA ADD CONSTRAINT COD_SIGLAPK PRIMARY KEY(COD_SIGLA);

ALTER TABLE TIPO_SIGLA ADD CONSTRAINT ID_TIPO_SIGLAPK PRIMARY KEY(ID_TIPO_SIGLA);

ALTER TABLE PACIENTES ADD CONSTRAINT ID_PACIENTE_PK PRIMARY KEY(ID);

ALTER TABLE USUARIO ADD CONSTRAINT ID_USUARIO_PK PRIMARY KEY(ID);